### ISSUE TITLE
Status of Cython compatibility

### ISSUE THREAD

**Issue by lysnikolaou** [Quansight-Labs/free-threaded-compatibility#4]
First PR opened on cython/cython#6137.

This allows the test suite to run. All of the falures are related to the `refnanny`.

https://github.com/cython/cython/pull/6147 enables vectorcall and fixes issues related to compiling in C99 mode.

**Comment by scoder** [comment]
https://github.com/cython/cython/pull/6137 was merged

**Comment by rgommers** [comment]
Awesome, thanks @scoder and @lysnikolaou!

**Comment by ngoldbaum** [comment]
I noticed today there are some cython tests that assume `PyObject` has an `ob_refcnt` field. I also saw a segfault in `parallel.parallel_exc_replace`, which uses `with gil`. It doesn't particularly surprise me that `with gil` is broken. 

We should probably have a brainstorming session about how to deal with `prange` code that does `with gil`.

**Comment by da-woods** [comment]
> We should probably have a brainstorming session about how to deal with `prange` code that does `with gil`.

I think there's a number of levels of that:
* There's some user-code that assumes `with gil` can be used a lock around non-parallel bits of their code. That's never really been the right thing to do and probably isn't Cython's problem or your problem to fix.
* There's some general Cython-generated code that isn't thread safe. That isn't specifically a `prange` problem since you could likely reproduce bugs with any threading mechanism. It should probably be fixed for nogil builds but it'll likely be a long process of finding the corner-cases. Avoiding borrowed references may solve a lot.
* There's bit of Cython's internal code to do with `prange/parallel` that uses the GIL as a lock to juggle exception state between the Python interpreter and local variables. For that I suspect we'll need to guard it with a mutex in the nogil builds.
* Eventually we'll probably want a nice way of doing `prange` that contains Python code for nogil builds (without having to wrap everything in meaningless `with gil:` blocks). That's a future problem since it's a new feature rather than a bugfix.

**Comment by ngoldbaum** [comment]
Thanks for that @da-woods!

One thing in response to what you wrote:

> Avoiding borrowed references may solve a lot.

This seems worth doing. Not every case is unsafe and it's probably unwise to manually convert every borrowed reference usage in human-authored C API code, but there's no reason for cython to use unsafe C API constructions when there are safe alternatives available.

I spent some time working on cython this morning and opened https://github.com/cython/cython/issues/6154 to report what I found about the test suite in the nogil build.

**Comment by da-woods** [comment]
> > Avoiding borrowed references may solve a lot.
> 
> This seems worth doing. Not every case is unsafe and it's probably unwise to manually convert every borrowed reference usage in human-authored C API code, but there's no reason for cython to use unsafe C API constructions when there are safe alternatives available.

I meant setting the `CYTHON_AVOID_BORROWED_REFS` flag (which isn't perfect and doesn't cover everything but does a lot)

**Comment by lysnikolaou** [comment]
Nightly wheels are up on https://anaconda.org/scientific-python-nightly-wheels/cython.

**Comment by ngoldbaum** [comment]
The PR that adds a new directive to declare free-threaded support was merged: https://github.com/cython/cython/pull/6242

**Comment by lysnikolaou** [comment]
> The PR that adds a new directive to declare free-threaded support was merged: https://github.com/cython/cython/pull/6242

That means that NumPy and SciPy can now be updated to use the new directive. I'll work on updating the docs on our website and adding the directive to pandas next.

**Comment by lysnikolaou** [comment]
Closing in favor of the upstream issue.
